schema_version: 1

context:
  name: redcamel
  version: "0.1.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/redcamel-${{ version }}.tar.gz
  sha256: cd48206a3ee7bd5b3a5b261fdace223e63de28b93b7e42986367ec1d2cf2b7b6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - redcamel = redcamel:main

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.8.13,<0.9.0
    - pip
  run:
    - python >=${{ python_min }}
    - chemformula >=1.2
    - python-graphviz >=0.20
    - ipywidgets >=8
    - matplotlib-base >=3.7
    - h5py >=3.11
    - numba >=0.58
    - numpy >=1.2
    - plopp >=23
    - scipp >=23
    - scipy >=1.10

tests:
  - python:
      imports:
        - redcamel
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://codeberg.org/FlashREMI/RedCamel
  repository: https://codeberg.org/FlashREMI/RedCamel
  summary: GUI tool to simulate Reaction Microscope detector images.
  license: GPL-3.0-or-later
  license_file:
  - LICENSES/
  - "REUSE.toml"
  - "CITATION.cff"

extra:
  recipe-maintainers:
  - HLinde
